catalogs:
  frontend:
    "@iconify-json/fluent": "^1.2.26"
    "@unocss/reset": "^66.3.3"
    "clsx": "^2.1.1"
    "jotai": "^2.12.5"
    "next": "15.3.1"
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "remeda": "^2.25.0"
    "unocss": "^66.3.3"
    "zod": "^4.0.5"
  type:
    "@types/chrome": "^0.1.0"
    "@types/node": "^20.19.7"
    "@types/react": "^19.1.8"
    "@types/react-dom": "^19.1.6"
  lint:
    "@eslint-react/eslint-plugin": "^1.52.3"
    "@next/eslint-plugin-next": "^15.3.5"
    "@typescript-eslint/eslint-plugin": "^8.36.0"
    "@typescript-eslint/parser": "^8.36.0"
    "@zjutjh/eslint-config": "^0.7.3"
    "eslint": "^9.31.0"
    "eslint-config-next": "15.3.1"
    "eslint-config-prettier": "^10.1.5"
    "eslint-plugin-format": "^1.0.1"
    "eslint-plugin-prettier": "^5.5.1"
    "eslint-plugin-react-hooks": "^5.2.0"
    "eslint-plugin-react-refresh": "^0.4.20"
    "prettier": "^3.6.2"
  infra:
    "@unocss/postcss": "^66.3.3"
    "glob": "^11.0.3"
    "jiti": "^2.4.2"
    "postcss-flexbugs-fixes": "^5.0.2"
    "postcss-import": "^16.1.1"
    "postcss-preset-env": "^10.2.4"
    "simple-git-hooks": "^2.13.0"
    "tsdown": "^0.12.9"
    "typescript": "^5.8.3"
